// Create the context menu item when the extension is installed.
chrome.runtime.onInstalled.addListener(() => {
    chrome.contextMenus.create({
      id: "get-ai-recommendations",
      title: "Get AI Recommendations for selected text",
      contexts: ["selection"]
    });
    console.log('AI Assistant: Context menu created.');
  });

  // Listen for a click on our context menu item (for Google Docs, etc.).
  chrome.contextMenus.onClicked.addListener((info, tab) => {
    if (info.menuItemId === "get-ai-recommendations" && info.selectionText) {
      console.log('AI Assistant (Background): Triggered by context menu.');
      chrome.sidePanel.open({ tabId: tab.id });
      triggerGetRecommendations(info.selectionText);
    }
  });

  // Listen for messages from the content script (for simple websites).
  chrome.runtime.onMessage.addListener((message, sender) => {
      if (message.type === 'GET_RECOMMENDATIONS') {
          console.log('AI Assistant (Background): Triggered automatically.');
          chrome.sidePanel.open({ tabId: sender.tab.id });
          triggerGetRecommendations(message.text);
      }
  });

  // Central function to call the AI.
  function triggerGetRecommendations(text) {
      chrome.runtime.sendMessage({ type: 'SHOW_LOADING' });

      chrome.storage.sync.get(['apiKey', 'contextContent'], async (result) => {
          const { apiKey, contextContent } = result;

          if (!apiKey) {
              chrome.runtime.sendMessage({ type: 'SHOW_ERROR', error: 'API Key not set. Please set it in the options.' });
              return;
          }

          let prompt = `You are an expert writing assistant. A user has provided a piece of text and needs help with the next sentence. Your task is to provide three distinct, creative, and contextually relevant suggestions for the sentence that should follow the provided text. The user's text is: "${text}"`;

          if (contextContent) {
              prompt += `\n\nAlso, consider this additional context provided by the user:\n---CONTEXT---\n${contextContent}\n---END CONTEXT---`;
          }

          prompt += `\n\nGenerate three suggestions. IMPORTANT: Your entire response must be ONLY a single, valid JSON array of strings, with no other text or explanations. Example: ["First suggestion.", "Second suggestion.", "A third, different idea."]`

          const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${apiKey}`;
          const payload = { contents: [{ role: "user", parts: [{ text: prompt }] }] };

          try {
              const response = await fetch(apiUrl, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) });

              if (!response.ok) {
                  throw new Error(`API Error: ${response.status}. Check your API Key in the options.`);
              }

              const result = await response.json();

              if (result.candidates && result.candidates.length > 0) {
                  const rawText = result.candidates[0].content.parts[0].text;
                  const cleanedText = rawText.trim().replace(/^```json\s*/, '').replace(/\s*```$/, '');
                  const suggestions = JSON.parse(cleanedText);
                  chrome.runtime.sendMessage({ type: 'SHOW_RECOMMENDATIONS', data: suggestions });
              } else {
                   throw new Error("No suggestions were generated by the AI.");
              }
          } catch (error) {
              console.error('AI Assistant (Background) Error:', error);
              chrome.runtime.sendMessage({ type: 'SHOW_ERROR', error: error.message });
          }
      });
  }

  // Open side panel when the user clicks the extension's toolbar icon.
  chrome.action.onClicked.addListener((tab) => {
      chrome.sidePanel.open({ tabId: tab.id });
  });
